//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeLan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeLan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Blog_Son.Resources.HomeLan", typeof(HomeLan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkında.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sakarya Üniversitesi Bilgisayar Mühendisliği bölümünde okuyorum.
        ///Amacım teknoloji dünyasına ufakta olsa bir katkı sağlamak. Bloğumda her konudan yazı bulabileceksiniz. Aklıma takılan merak ettiğim ne varsa sizinle paylaşmaya çalışacağım..
        /// </summary>
        public static string Aciklama {
            get {
                return ResourceManager.GetString("Aciklama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsminiz.
        /// </summary>
        public static string Adiniz {
            get {
                return ResourceManager.GetString("Adiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neyi aramak istiyorsun?.
        /// </summary>
        public static string Arama {
            get {
                return ResourceManager.GetString("Arama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arşiv.
        /// </summary>
        public static string Arsiv {
            get {
                return ResourceManager.GetString("Arsiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık.
        /// </summary>
        public static string Baslik {
            get {
                return ResourceManager.GetString("Baslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beğeniler.
        /// </summary>
        public static string Begeniler {
            get {
                return ResourceManager.GetString("Begeniler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış Yap.
        /// </summary>
        public static string CikisYap {
            get {
                return ResourceManager.GetString("CikisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgisayar.
        /// </summary>
        public static string Computer {
            get {
                return ResourceManager.GetString("Computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Değiştir.
        /// </summary>
        public static string Degistir {
            get {
                return ResourceManager.GetString("Degistir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devamını oku.
        /// </summary>
        public static string Devaminioku {
            get {
                return ResourceManager.GetString("Devaminioku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Düzenle.
        /// </summary>
        public static string Duzenle {
            get {
                return ResourceManager.GetString("Duzenle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ekle.
        /// </summary>
        public static string Ekle {
            get {
                return ResourceManager.GetString("Ekle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket alanı zorunludur.
        /// </summary>
        public static string EtiketAlan {
            get {
                return ResourceManager.GetString("EtiketAlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket Ekle.
        /// </summary>
        public static string EtiketEkle {
            get {
                return ResourceManager.GetString("EtiketEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiketler.
        /// </summary>
        public static string Etiketler {
            get {
                return ResourceManager.GetString("Etiketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Etiket Sil.
        /// </summary>
        public static string EtiketSil {
            get {
                return ResourceManager.GetString("EtiketSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm Etiketler.
        /// </summary>
        public static string EtiketTum {
            get {
                return ResourceManager.GetString("EtiketTum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu etiketi gerçekten silmek istiyor musun?.
        /// </summary>
        public static string Gercekten {
            get {
                return ResourceManager.GetString("Gercekten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu makaleyi gerçekten silmek istiyor musun?.
        /// </summary>
        public static string GercektenMaka {
            get {
                return ResourceManager.GetString("GercektenMaka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş Yap.
        /// </summary>
        public static string GirisYap {
            get {
                return ResourceManager.GetString("GirisYap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gönder.
        /// </summary>
        public static string Gonder {
            get {
                return ResourceManager.GetString("Gonder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Görüntülenme.
        /// </summary>
        public static string Goruntulenme {
            get {
                return ResourceManager.GetString("Goruntulenme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncel.
        /// </summary>
        public static string Guncel {
            get {
                return ResourceManager.GetString("Guncel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haritada yerinizi bulun..
        /// </summary>
        public static string Harita {
            get {
                return ResourceManager.GetString("Harita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldin.
        /// </summary>
        public static string Hosgeldin {
            get {
                return ResourceManager.GetString("Hosgeldin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoşgeldiniz.
        /// </summary>
        public static string Hoşgeldiniz {
            get {
                return ResourceManager.GetString("Hoşgeldiniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İrtibat için lütfen boş bırakılan alanları doldurunuz..
        /// </summary>
        public static string Iletisim1 {
            get {
                return ResourceManager.GetString("Iletisim1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İngilizce.
        /// </summary>
        public static string Ingilizce {
            get {
                return ResourceManager.GetString("Ingilizce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Düzenle.
        /// </summary>
        public static string KatDuzen {
            get {
                return ResourceManager.GetString("KatDuzen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategoriler.
        /// </summary>
        public static string Kategoriler {
            get {
                return ResourceManager.GetString("Kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategori Ekle.
        /// </summary>
        public static string KatEkle {
            get {
                return ResourceManager.GetString("KatEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kayıt Ol.
        /// </summary>
        public static string Kaydol {
            get {
                return ResourceManager.GetString("Kaydol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dil.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listeye geri dön.
        /// </summary>
        public static string ListeGeri {
            get {
                return ResourceManager.GetString("ListeGeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makaleler.
        /// </summary>
        public static string Makaleler {
            get {
                return ResourceManager.GetString("Makaleler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makale Sil.
        /// </summary>
        public static string MakaleSil {
            get {
                return ResourceManager.GetString("MakaleSil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makale Yaz.
        /// </summary>
        public static string MakaleYaz {
            get {
                return ResourceManager.GetString("MakaleYaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makaleyi yazınız..
        /// </summary>
        public static string MakaYaz {
            get {
                return ResourceManager.GetString("MakaYaz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old.
        /// </summary>
        public static string Maziden {
            get {
                return ResourceManager.GetString("Maziden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesajınız.
        /// </summary>
        public static string Mesaj {
            get {
                return ResourceManager.GetString("Mesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dakika Önce.
        /// </summary>
        public static string Once {
            get {
                return ResourceManager.GetString("Once", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu makaleyi paylaş.
        /// </summary>
        public static string Paylas {
            get {
                return ResourceManager.GetString("Paylas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popüler Makaleler.
        /// </summary>
        public static string PopularMakaleler {
            get {
                return ResourceManager.GetString("PopularMakaleler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reklam.
        /// </summary>
        public static string Reklam {
            get {
                return ResourceManager.GetString("Reklam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2009 yılından bu yana faaliyette olan usluer.net, kişisel blog kategorisinde, bağımsız bir blogdur.
        ///         Kuruluş amacı ticari faaliyette bulunmak veya kazanç elde etmek değildir.
        ///         Bunun yanında usluer.net’i ayda yaklaşık 20.000 kişi ziyaret etmektedir.
        ///
        ///        Usluer.net’te blogun periyodik giderlerini, tanıtım harcamalarını ve gelişerek daha iyi hizmet sunması ile ilgili diğer
        ///         masraflarını karşılamak üzere, bağış kapsamında kabul edilen belirli ücretler karşılığında tanıtım ve re [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Reklam1 {
            get {
                return ResourceManager.GetString("Reklam1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanıtım yazısı fiyatı 80 TL‘dir. Yazı içeriğinin tarafımızca hazırlanması istenirse 100 TL‘dir.
        ///            Yayınlanacak olan tanıtım yazısı en az 250 kelimeden oluşmalı ve özgün olmalıdır.
        ///            Yazıya ait başlık, boşluklar dahil olmak üzere en fazla 55 karakter olabilir ve URL içeremez.
        ///            Yazı içerisinden tek bir siteye ve en fazla 3 adet link çıkışı yapılabilir.
        ///            Yazı içerisinde en az 1 görsel kullanılmalıdır. Görsel çözünürlüğü 800×300 pikselden düşük ve hareketli olamaz.  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Reklam2 {
            get {
                return ResourceManager.GetString("Reklam2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanıtım Yazısı.
        /// </summary>
        public static string ReklamBaslik {
            get {
                return ResourceManager.GetString("ReklamBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıya Rol Atayınız.
        /// </summary>
        public static string RolAta {
            get {
                return ResourceManager.GetString("RolAta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol Ekle.
        /// </summary>
        public static string RolEkle {
            get {
                return ResourceManager.GetString("RolEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller.
        /// </summary>
        public static string Roller {
            get {
                return ResourceManager.GetString("Roller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saat Önce.
        /// </summary>
        public static string SaatOnce {
            get {
                return ResourceManager.GetString("SaatOnce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silerken hata oluştu..
        /// </summary>
        public static string SilHata {
            get {
                return ResourceManager.GetString("SilHata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şimdi.
        /// </summary>
        public static string Simdi {
            get {
                return ResourceManager.GetString("Simdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son Makaleler.
        /// </summary>
        public static string SonMakaleler {
            get {
                return ResourceManager.GetString("SonMakaleler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tarihinde.
        /// </summary>
        public static string Tarihinde {
            get {
                return ResourceManager.GetString("Tarihinde", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türkçe.
        /// </summary>
        public static string Turkce {
            get {
                return ResourceManager.GetString("Turkce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemize üye değilseniz hemen üye olun..
        /// </summary>
        public static string Uye {
            get {
                return ResourceManager.GetString("Uye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen etiketler arasına virgül koyunuz..
        /// </summary>
        public static string Virgul {
            get {
                return ResourceManager.GetString("Virgul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayım Tarihi.
        /// </summary>
        public static string Yayim {
            get {
                return ResourceManager.GetString("Yayim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayında mı?.
        /// </summary>
        public static string Yayinda {
            get {
                return ResourceManager.GetString("Yayinda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yayınla.
        /// </summary>
        public static string Yayinla {
            get {
                return ResourceManager.GetString("Yayinla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yazar.
        /// </summary>
        public static string Yazar {
            get {
                return ResourceManager.GetString("Yazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemen kısaca kendimden bahsedeyim. Almanya’nın Duisburg kentinde, 88’in Temmuz ayında doğmuşum. 
        ///        Ailemin Türkiye’ye geri dönme kararı ile sadece 3 yaşında olan ben,
        ///         Almanya’dan hiçbir hatıra alamadan vatanıma geri dönmüşüm. Hayal meyal bir şeyler hatırlıyorum ama bu hatıraların 
        ///        Almanya’da çekilmiş fotoğraflarıma bakmamdan dolayı oluştuğunu düşünmekteyim.
        ///   
        ///        İlköğretimi büyüdüğüm yer olan Dereköy(kütahya)’ de tamamladım. 
        ///        Kütahya Ali Güral Anadolu Lisesi’nde ” [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Yazi {
            get {
                return ResourceManager.GetString("Yazi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlar.
        /// </summary>
        public static string Yorumlar {
            get {
                return ResourceManager.GetString("Yorumlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı alanı zorunludur..
        /// </summary>
        public static string zorunluAdi {
            get {
                return ResourceManager.GetString("zorunluAdi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başlık alanı zorunludur..
        /// </summary>
        public static string zorunluBaslik {
            get {
                return ResourceManager.GetString("zorunluBaslik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı E-Mail alanı zorunludur..
        /// </summary>
        public static string zorunluEmail {
            get {
                return ResourceManager.GetString("zorunluEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İçerik alanı zorunludur..
        /// </summary>
        public static string zorunluIcerik {
            get {
                return ResourceManager.GetString("zorunluIcerik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola alanı zorunludur..
        /// </summary>
        public static string zorunluPas {
            get {
                return ResourceManager.GetString("zorunluPas", resourceCulture);
            }
        }
    }
}
