//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blog_Son.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int Id { get; set; }
        public string Adi { get; set; }
        public string Baslik { get; set; }
        public string Icerik { get; set; }
        public Nullable<int> MakaleID { get; set; }
        public System.DateTime EklenmeTarihi { get; set; }
        public Nullable<bool> Aktif { get; set; }
        public Nullable<System.Guid> YazarID { get; set; }
    
        public virtual Makale Makale { get; set; }
    }
}
